//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMBaoCao
    {
        public System.Guid Id { get; set; }
        public string TieuDe { get; set; }
        public string NOIDUNG { get; set; }
        public string TEN { get; set; }
        public string THUTUC { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
