//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMCauHinh
    {
        public System.Guid Id { get; set; }
        public string ManHinh { get; set; }
        public string CPU { get; set; }
        public string PIN { get; set; }
        public string RAM { get; set; }
        public Nullable<System.DateTime> NGAYSX { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
        public string DUNGLUONG { get; set; }
        public string MOTA { get; set; }
        public Nullable<System.Guid> IdSanPham { get; set; }
        public Nullable<System.Guid> IdLoaiCauHinh { get; set; }
    
        public virtual CMTuDien CMTuDien { get; set; }
        public virtual DMSanPham DMSanPham { get; set; }
    }
}
