//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMCart
    {
        public System.Guid Id { get; set; }
        public string TinNhan { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<System.DateTime> THOIGIANTAO { get; set; }
        public Nullable<System.Guid> IdLoaiGD { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> IdTrangThai { get; set; }
    
        public virtual CMTuDien CMTuDien { get; set; }
        public virtual CMTuDien CMTuDien1 { get; set; }
        public virtual HTUser HTUser { get; set; }
    }
}
