//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMCartDetail
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdSanPham { get; set; }
        public Nullable<int> UuTien { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
    
        public virtual DMSanPham DMSanPham { get; set; }
    }
}
