//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMTinhThanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMTinhThanh()
        {
            this.DMTinhThanh1 = new HashSet<DMTinhThanh>();
        }
    
        public System.Guid Id { get; set; }
        public string Ten { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UuTien { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.Guid> IdCapTren { get; set; }
        public Nullable<System.Guid> IdLoaiTinhThanh { get; set; }
    
        public virtual CMTuDien CMTuDien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMTinhThanh> DMTinhThanh1 { get; set; }
        public virtual DMTinhThanh DMTinhThanh2 { get; set; }
    }
}
