//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HTMenu()
        {
            this.HTMenu1 = new HashSet<HTMenu>();
            this.HTRoleMenus = new HashSet<HTRoleMenu>();
        }
    
        public System.Guid Id { get; set; }
        public string Icon { get; set; }
        public string Ten { get; set; }
        public string Controller { get; set; }
        public string Link { get; set; }
        public string Mota { get; set; }
        public Nullable<System.Guid> IdParent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTMenu> HTMenu1 { get; set; }
        public virtual HTMenu HTMenu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTRoleMenu> HTRoleMenus { get; set; }
    }
}
