//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTRoleMenu
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdRole { get; set; }
        public Nullable<System.Guid> IdMenu { get; set; }
        public Nullable<int> UuTien { get; set; }
        public string Mota { get; set; }
    
        public virtual HTMenu HTMenu { get; set; }
        public virtual HTRole HTRole { get; set; }
    }
}
