//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HTUser()
        {
            this.DMCarts = new HashSet<DMCart>();
            this.DMPhongBans = new HashSet<DMPhongBan>();
            this.DMSanPhams = new HashSet<DMSanPham>();
            this.HSCmts = new HashSet<HSCmt>();
            this.HSTinNhans = new HashSet<HSTinNhan>();
            this.HTRoles = new HashSet<HTRole>();
        }
    
        public System.Guid Id { get; set; }
        public string HoTen { get; set; }
        public string TenKhongDau { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.Guid> IdAnh { get; set; }
        public Nullable<System.Guid> IDLoaiTaiKhoan { get; set; }
    
        public virtual CMTuDien CMTuDien { get; set; }
        public virtual DMAnh DMAnh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMCart> DMCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMPhongBan> DMPhongBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMSanPham> DMSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HSCmt> HSCmts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HSTinNhan> HSTinNhans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTRole> HTRoles { get; set; }
    }
}
